language: node_js

node_js:
    - 7.4
    - 7.5

env:
    # test across multiple versions of Neo4j:
    - NEO4J_VERSION="3.0.6"
    - NEO4J_VERSION="2.3.9"


before_install:
    # install Neo4j locally:
    - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - neo4j-community-$NEO4J_VERSION/bin/neo4j start

install:
- echo "hola"
