language: ruby

matrix:
  fast_finish: true

env:
    # test across multiple versions of Neo4j:
    - NEO4J_VERSION="3.0.6"
    - NEO4J_VERSION="2.3.9"
    - NEO4J_VERSION="2.3.sss9"
    - NEO4J_VERSION="2.dd3.9"

install:
- if [ "${NEO4J_VERSION}" = "3.0.6" ]; then sleep 60; fi
- if [ "${NEO4J_VERSION}" = "2.3.9" ]; then sleep 180; fi
- if [ "${NEO4J_VERSION}" = "2.3.sss9" ]; then sleep 65; fi
- if [ "${NEO4J_VERSION}" = "2.dd3.9" ]; then sleep 10; fi
- locate mysqlclient
