language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=7.5
  
before_install:
- nvm use $NODE_VERSION
- wget dist.neo4j.org/neo4j-community-3.0.6-unix.tar.gz
- tar -xzf neo4j-community-3.0.6-unix.tar.gz
- neo4j-community-3.0.6/bin/neo4j start


script:
- yarn test,

dist: precise

